#!/usr/bin/env python3
"""
Python Skill Matrix CLI.

Commands:
  status                Print phase, goal, assessment status, next action.
  complete-baseline     Mark baseline assessment as completed in state.md.
  generate-review-queue Compute matrix/review_queue.md from skill_matrix.md.
  generate-dashboard    Regenerate the dynamic section of dashboard.md.
  generate-today        Write TODAY.md for the top-priority topic.

Usage:
  python main.py <command>
"""

import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).parent

FREQ_WEIGHTS = {"Very High": 4, "High": 3, "Medium": 2, "Low": 1}
FRESHNESS_WEIGHTS = {"Fresh": 1, "Medium": 2, "Stale": 3, "Critical": 4}

DOMAIN_DIRS = {
    "Functional Python": "functional_python",
    "OOP": "oop",
    "Advanced Syntax": "advanced_syntax",
    "Python Internals": "python_internals",
    "Data Structures": "data_structures",
    "Basics": "basics",
    "Concurrency": "concurrency",
    "Standard Library": "standard_library",
    "Testing & Debugging": "testing",
}


def _generated_note(command):
    return (
        f"<!-- Generated by `python main.py {command}` on {date.today()}."
        f" Re-run to update. Do not edit this section manually. -->"
    )


# ─── State parsing ────────────────────────────────────────────────────────────

def _read_yaml_block(text):
    m = re.search(r"```yaml\n(.*?)```", text, re.DOTALL)
    return m.group(1) if m else ""


def _get_field(yaml_text, key):
    """Read a top-level YAML field, stripping inline comments."""
    m = re.search(rf"^{re.escape(key)}:\s*(.+)$", yaml_text, re.MULTILINE)
    if not m:
        return None
    return m.group(1).strip().split("#")[0].strip()


def _set_field(text, key, new_value):
    """Replace a top-level YAML field value in-place, preserving comments."""
    return re.sub(
        rf"^({re.escape(key)}:)\s*\S+",
        rf"\1 {new_value}",
        text,
        flags=re.MULTILINE,
    )


def read_state():
    text = (ROOT / "state.md").read_text(encoding="utf-8")
    yaml = _read_yaml_block(text)
    return {
        "baseline_done": _get_field(yaml, "baseline_assessment_completed") == "true",
        "goal": _get_field(yaml, "active_goal") or "not_selected",
        "phase": _get_field(yaml, "phase") or "calibration",
        "next_action": _get_field(yaml, "next_action") or "",
    }


def update_state(updates: dict):
    path = ROOT / "state.md"
    text = path.read_text(encoding="utf-8")
    for key, value in updates.items():
        text = _set_field(text, key, value)
    path.write_text(text, encoding="utf-8")


# ─── Skill matrix parsing ─────────────────────────────────────────────────────

def read_skill_matrix():
    path = ROOT / "matrix" / "skill_matrix.md"
    topics = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| "):
            continue
        parts = [p.strip() for p in line.split("|")[1:-1]]
        if len(parts) < 5 or parts[0] in ("Domain", "---", ""):
            continue
        if parts[1].startswith("---"):
            continue
        domain, topic, mastery_str, freshness, freq = parts[:5]
        mastery_raw = mastery_str.split("/")[0]
        mastery = int(mastery_raw) if mastery_raw.isdigit() else 0
        topics.append({
            "domain": domain,
            "topic": topic,
            "mastery": mastery,
            "freshness": freshness,
            "frequency": freq,
        })
    return topics


def priority(t, goal=""):
    fw = FREQ_WEIGHTS.get(t["frequency"], 0)
    weakness = 10 - t["mastery"]
    if goal in ("interview_campaign", "single_interview_prep"):
        # Interview mode: no freshness multiplier — every session is urgent
        return fw * weakness
    return fw * weakness * FRESHNESS_WEIGHTS.get(t["freshness"], 1)


def ranked(topics, goal=""):
    scored = [{**t, "priority": priority(t, goal)} for t in topics]
    return sorted(scored, key=lambda t: t["priority"], reverse=True)


# ─── Topic file path heuristic ────────────────────────────────────────────────

def _topic_slug(name):
    s = re.sub(r"[`*]", "", name)
    s = s.replace(" vs ", "_vs_").replace(" / ", "_").replace("/", "_").replace(" & ", "_and_")
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"\s+", "_", s.strip()).lower()
    return re.sub(r"_+", "_", s)


def topic_path(t):
    domain_dir = DOMAIN_DIRS.get(t["domain"], t["domain"].lower().replace(" ", "_"))
    slug = _topic_slug(t["topic"])
    candidate = ROOT / "domains" / domain_dir / f"{slug}.md"
    rel = f"domains/{domain_dir}/{slug}.md"
    return rel if candidate.exists() else f"domains/{domain_dir}/"


# ─── Commands ─────────────────────────────────────────────────────────────────

def cmd_status():
    state = read_state()
    topics = read_skill_matrix()
    assessed = sum(1 for t in topics if t["mastery"] > 0)
    phase_label = state["phase"].replace("_", " ").title()
    goal_label = state["goal"].replace("_", " ").title()
    print(f"Phase:       {phase_label}")
    print(f"Goal:        {goal_label}")
    print(f"Assessment:  {'Completed' if state['baseline_done'] else 'Not started'}")
    print(f"Next action: {state['next_action']}")
    print(f"Topics:      {len(topics)} documented, {assessed} assessed (mastery > 0)")
    if assessed > 0:
        top = ranked(topics, state["goal"])[0]
        print(f"Top priority: {top['topic']} (score {top['priority']})")


def cmd_complete_baseline():
    state = read_state()
    if state["baseline_done"]:
        print("Already marked as completed.")
        return
    update_state({
        "baseline_assessment_completed": "true",
        "phase": "goal_selection",
        "next_action": "goals/README.md",
    })
    print("Baseline assessment marked as completed.")
    print("Phase → goal_selection  |  Next action → goals/README.md")
    print()
    print("Next step: open goals/README.md, choose a goal,")
    print("then set active_goal in state.md and run:")
    print("  python main.py generate-review-queue")
    print("  python main.py generate-dashboard")
    print("  python main.py generate-today")


def cmd_generate_review_queue():
    state = read_state()
    topics = read_skill_matrix()
    goal = state["goal"]
    r = ranked(topics, goal)
    today = date.today().isoformat()

    formula = (
        "`freq_weight × (10 − mastery)` (interview mode — no freshness multiplier)"
        if goal in ("interview_campaign", "single_interview_prep")
        else "`freq_weight × (10 − mastery) × freshness_weight`"
    )

    lines = [
        _generated_note("generate-review-queue"),
        "",
        "# Review Queue",
        "",
        f"*Goal: {goal.replace('_', ' ').title()} · Last computed: {today}*",
        f"*Formula: {formula}*",
        "",
        "## Top 20",
        "",
        "| # | Topic | Domain | Mastery | Freq | Freshness | Priority |",
        "|---|---|---|---:|---|---|---:|",
    ]
    for i, t in enumerate(r[:20], 1):
        lines.append(
            f"| {i} | {t['topic']} | {t['domain']}"
            f" | {t['mastery']}/10 | {t['frequency']} | {t['freshness']} | {t['priority']} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Full List",
        "",
        "| Topic | Domain | Mastery | Freq | Freshness | Priority |",
        "|---|---|---:|---|---|---:|",
    ]
    for t in r:
        lines.append(
            f"| {t['topic']} | {t['domain']}"
            f" | {t['mastery']}/10 | {t['frequency']} | {t['freshness']} | {t['priority']} |"
        )

    out = ROOT / "matrix" / "review_queue.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Written: matrix/review_queue.md")
    if r:
        print(f"Top priority: {r[0]['topic']} (score {r[0]['priority']})")


def cmd_generate_dashboard():
    state = read_state()
    topics = read_skill_matrix()
    goal = state["goal"]
    phase = state["phase"]
    r = ranked(topics, goal)
    assessed = sum(1 for t in topics if t["mastery"] > 0)
    today = date.today().isoformat()

    phase_label = {"calibration": "Calibration", "goal_selection": "Goal Selection", "active": "Active"}.get(phase, phase.title())
    goal_label = goal.replace("_", " ").title() if goal != "not_selected" else "Not Selected"

    lines = [
        _generated_note("generate-dashboard"),
        "",
        f"> **Phase: {phase_label} · Goal: {goal_label}**",
    ]

    if phase == "calibration":
        lines += [
            "> The baseline assessment has not been completed.",
            "> → **[baseline_assessment/README.md](baseline_assessment/README.md)**",
        ]
    elif phase == "goal_selection":
        lines += [
            "> Assessment complete. Choose a goal.",
            "> → **[goals/README.md](goals/README.md)**",
        ]
    elif goal in ("interview_campaign", "single_interview_prep"):
        lines += [
            "> Active — interview preparation mode.",
            "> → **[goals/interview_campaign.md](goals/interview_campaign.md)**",
        ]
    else:
        lines.append(f"> Active — {goal_label} mode.")

    lines += [
        "> *(Update this when phase or goal changes — see [state.md](state.md))*",
        "",
        "---",
        "",
        f"**Assessment:** {'Completed' if state['baseline_done'] else 'Not Started'}"
        f" · **Goal:** {goal_label} · *Last updated: {today}*",
        f"**Topics:** {len(topics)} documented · {assessed} assessed",
        "",
        "→ **[START_HERE.md](START_HERE.md)** — phases, decision tree, file map",
        "→ **[state.md](state.md)** — current phase, goal, and next action",
        "",
        "---",
        "",
    ]

    # Phase-specific next action
    if phase == "calibration":
        lines += [
            "## Next Action: Complete Baseline Assessment",
            "",
            "| | |",
            "|---|---|",
            "| **File** | [baseline_assessment/README.md](baseline_assessment/README.md) |",
            "| **Time** | 60–90 minutes |",
            "| **Outcome** | Skill profile · calibrated review queue · realistic priorities |",
            "",
            "After the audit, choose a goal: **Interview Campaign** · **Long-Term Mastery**"
            " · **Domain Sprint** · **Maintenance**",
            "",
            "→ [goals/README.md](goals/README.md)",
        ]
    elif phase == "goal_selection":
        lines += [
            "## Next Action: Choose a Goal",
            "",
            "→ [goals/README.md](goals/README.md)",
            "",
            "| Goal | Use when |",
            "|---|---|",
            "| Interview Campaign | Active job search, multiple interviews |",
            "| Single Interview Prep | One specific upcoming interview |",
            "| Long-Term Mastery | No deadline, broad coverage |",
            "| Domain Sprint | One domain, end-to-end |",
            "| Maintenance | Keep existing knowledge fresh |",
        ]
    elif goal in ("interview_campaign", "single_interview_prep"):
        lines += ["## Today's Session — Interview Preparation", ""]
        if r:
            top = r[0]
            lines += [
                f"**Top priority:** {top['topic']}"
                f" (mastery {top['mastery']}/10 · {top['frequency']} freq · score {top['priority']})",
                f"→ [TODAY.md](TODAY.md)",
                "",
            ]
        lines += [
            "→ **[goals/interview_campaign.md](goals/interview_campaign.md)** — campaign status",
            "→ **[matrix/interview_mode.md](matrix/interview_mode.md)** — top 10 topics and risks",
        ]
    elif goal == "long_term_mastery":
        lines += ["## Today's Session — Long-Term Mastery", ""]
        if r:
            top = r[0]
            lines += [
                f"**Top priority:** {top['topic']}"
                f" (mastery {top['mastery']}/10 · priority {top['priority']})",
                f"→ [TODAY.md](TODAY.md)",
                "",
            ]
        lines.append("→ **[matrix/review_queue.md](matrix/review_queue.md)**")
    elif goal == "maintenance":
        lines += ["## Today's Session — Maintenance", ""]
        stale = [t for t in r if t["freshness"] in ("Stale", "Critical")][:5]
        if stale:
            lines.append("Stale and Critical topics only:")
            lines.append("")
            for t in stale:
                lines.append(
                    f"- **{t['topic']}** — {t['freshness']} · mastery {t['mastery']}/10"
                )
        else:
            lines.append("No stale or critical topics. Nothing to review today.")
        lines += ["", "→ **[goals/maintenance.md](goals/maintenance.md)**"]

    # Top priorities table — only if assessed data exists
    if assessed > 0:
        lines += [
            "",
            "---",
            "",
            "## Top Priorities",
            "",
            "| # | Topic | Domain | Mastery | Freq | Priority |",
            "|---|---|---|---:|---|---:|",
        ]
        for i, t in enumerate(r[:5], 1):
            lines.append(
                f"| {i} | {t['topic']} | {t['domain']}"
                f" | {t['mastery']}/10 | {t['frequency']} | {t['priority']} |"
            )
        lines += ["", "→ [Full review queue](matrix/review_queue.md)"]

    generated_block = "\n".join(lines)

    dash_path = ROOT / "dashboard.md"
    content = dash_path.read_text(encoding="utf-8")

    begin = "<!-- BEGIN:generated -->"
    end = "<!-- END:generated -->"
    pattern = rf"{re.escape(begin)}.*?{re.escape(end)}"

    replacement = f"{begin}\n{generated_block}\n{end}"

    if re.search(pattern, content, re.DOTALL):
        new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)
    else:
        # First run: insert after the h1 title
        new_content = re.sub(
            r"(# .+\n)",
            rf"\1\n{replacement}\n",
            content,
            count=1,
        )

    dash_path.write_text(new_content, encoding="utf-8")
    print("Written: dashboard.md")


def cmd_generate_today():
    state = read_state()
    topics = read_skill_matrix()
    goal = state["goal"]
    r = ranked(topics, goal)
    today = date.today().isoformat()

    candidates = (
        [t for t in r if t["freshness"] in ("Stale", "Critical")]
        if goal == "maintenance"
        else r
    )

    if not candidates:
        print("No eligible topics for current goal and filter.")
        return

    top = candidates[0]
    tpath = topic_path(top)

    goal_note = {
        "interview_campaign": "Interview Campaign — prioritise confident verbal explanation",
        "single_interview_prep": "Single Interview Preparation — time-boxed, high stakes",
        "long_term_mastery": "Long-Term Mastery — focus on depth and retention",
        "domain_sprint": "Domain Sprint — finish the roadmap step",
        "maintenance": "Maintenance — light review only, no new material",
    }.get(goal, goal.replace("_", " ").title())

    lines = [
        _generated_note("generate-today"),
        "",
        f"# Today's Session — {top['topic']}",
        "",
        "> **Note:** This file is only meaningful after baseline assessment and goal",
        "> selection. If you haven't run those yet, start at",
        "> [baseline_assessment/README.md](baseline_assessment/README.md).",
        "",
        "---",
        "",
        f"**Date:** {today}",
        f"**Time:** ~30 minutes",
        f"**Topic:** {top['topic']}"
        f" (mastery {top['mastery']}/10 · {top['frequency']} frequency · {top['freshness']})",
        f"**Goal:** {goal_note}",
        f"**Priority score:** {top['priority']}",
        "",
        "---",
        "",
        "## Step 1 — Recall (5 min)",
        "",
        f"Without opening any file, explain **{top['topic']}** aloud in 30 seconds.",
        "What is it? Why does it matter? Where does it trip people up?",
        "",
        "---",
        "",
        "## Step 2 — Read the topic (5 min)",
        "",
        f"→ [{top['topic']}]({tpath})",
        "",
        "Read only: the 30-second explanation and Mental model sections.",
        "Close the file. Explain again — what changed?",
        "",
        "---",
        "",
        "## Step 3 — Code reading (5 min)",
        "",
        "Open [code_reading/](code_reading/) and find a puzzle tagged to this topic.",
        "Write your prediction before revealing the answer.",
        "",
        "Predicted output: ___",
        "",
        "---",
        "",
        "## Step 4 — Drill (10 min)",
        "",
        f"Open [drills/](drills/) and find the drill file for this topic.",
        "Pick 2–3 exercises. Solve without looking at the answer first.",
        "",
        "---",
        "",
        "## Step 5 — Update (2 min)",
        "",
        "In [matrix/skill_matrix.md](matrix/skill_matrix.md):",
        "",
        f"- **{top['topic']}:** set Freshness → Fresh, Last Reviewed → {today}",
        f"- Mastery was **{top['mastery']}/10**. Adjust:",
        "  - Explained clearly, first try → +1 or +2",
        "  - Needed a hint → +0",
        "  - Got it wrong → −1",
        "",
        "If anything surprised you:",
        "→ [hall_of_pain.md](hall_of_pain.md) — add one entry",
        "",
        "---",
        "",
        "## Next session",
        "",
        "After updating skill_matrix.md, regenerate:",
        "```",
        "python main.py generate-review-queue",
        "python main.py generate-today",
        "```",
    ]

    (ROOT / "TODAY.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Written: TODAY.md")
    print(f"Topic:   {top['topic']} (priority {top['priority']})")


def cmd_next():
    """Run the full safe refresh sequence and print the next action."""
    print("── status ───────────────────────────────")
    cmd_status()
    print()
    print("── generate-review-queue ────────────────")
    cmd_generate_review_queue()
    print()
    print("── generate-dashboard ───────────────────")
    cmd_generate_dashboard()
    print()
    print("── generate-today ───────────────────────")
    cmd_generate_today()
    print()
    print("─────────────────────────────────────────")
    print("Next action: open TODAY.md")


def cmd_onboard():
    """Print the post-baseline onboarding guide."""
    state = read_state()
    step = 1

    print("Onboarding guide — follow these steps in order.")
    print()

    if not state["baseline_done"]:
        print(f"  {step}. Complete the baseline assessment.")
        print("     Open: baseline_assessment/README.md")
        print("     Time: 60–90 minutes")
        print("     Output: your scores per topic (0–5 scale)")
        step += 1
        print()
        print(f"  {step}. Transfer scores to skill_matrix.md.")
        print("     Open: matrix/skill_matrix.md")
        print("     Update the Mastery column for each assessed topic.")
        print("     Update the Freshness column to reflect today.")
        step += 1
        print()
        print(f"  {step}. Mark the baseline as complete.")
        print("     Run:  python main.py complete-baseline")
        step += 1
    else:
        print(f"  ✓  Baseline assessment completed.")

    print()

    if state["goal"] == "not_selected":
        print(f"  {step}. Choose your active goal.")
        print("     Open: goals/README.md")
        print("     Then set active_goal in state.md.")
        print("     Options: interview_campaign · single_interview_prep ·")
        print("              long_term_mastery · domain_sprint · maintenance")
        step += 1
    else:
        print(f"  ✓  Goal set: {state['goal'].replace('_', ' ')}")

    print()
    print(f"  {step}. Generate your personalised files.")
    print("     Run:  python main.py next")
    print("     Opens: TODAY.md with your top-priority session.")
    print()
    print("After each study session:")
    print("  - Update mastery and freshness in matrix/skill_matrix.md")
    print("  - Run: python main.py next")


# ─── Entry point ──────────────────────────────────────────────────────────────

COMMANDS = {
    "status": cmd_status,
    "complete-baseline": cmd_complete_baseline,
    "generate-review-queue": cmd_generate_review_queue,
    "generate-dashboard": cmd_generate_dashboard,
    "generate-today": cmd_generate_today,
    "next": cmd_next,
    "onboard": cmd_onboard,
}

USAGE = """\
Python Skill Matrix CLI

Commands:
  next                  Refresh everything and print: open TODAY.md.
  onboard               Step-by-step guide for after the baseline assessment.
  status                Print phase, goal, assessment status, next action.
  complete-baseline     Mark baseline assessment as completed in state.md.
  generate-review-queue Compute matrix/review_queue.md from skill_matrix.md.
  generate-dashboard    Regenerate the dynamic section of dashboard.md.
  generate-today        Write TODAY.md for the top-priority topic.

Usage:
  python main.py <command>
"""

if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] not in COMMANDS:
        print(USAGE)
        sys.exit(0 if len(sys.argv) < 2 else 1)
    COMMANDS[sys.argv[1]]()
